### ISSUE TITLE
Variable "searchExcerpt" does not exist.

### ISSUE THREAD

**Issue by mdominguez** [gudehus/searchexcerpt2#1]
Hi there,

When trying out the searchExcerpt.from(..) method I get the error that searchExcerpt does not exist. [view screenshot](https://cl.ly/cb30451ac1e8)
Plugin is definitely enabled.

Thanks!

**Comment by gudehus** [comment]
You looked at the old documentation of the craft 2 version. In Craft 3 you have to call searchExcerpt directly.

You can use searchExcerpt as a function

{{ searchExcerpt(text, searchterm[[, padding][, class]]) }}

or as a Twig filter

{{ text|searchExcerpt(searchterm[[, padding][, class]]) }}

I fixed the wrong documentation link in the last version.

mit freundlichen Grüßen
Jörg Gudehus

IT-Consultant

Holsteinische Straße 4
10717 Berlin
+49 151 15674619
gudehus@mac.com
www.joerggudehus.de


Pflichtinformationen gemäß Artikel 13 DSGVO
Im Falle des Erstkontakts sind wir gemäß Art. 12, 13 DSGVO verpflichtet, Ihnen folgende datenschutzrechtliche Pflichtinformationen zur Verfügung zu stellen: Wenn Sie uns per E-Mail kontaktieren, verarbeiten wir Ihre personenbezogenen Daten nur, soweit an der Verarbeitung ein berechtigtes Interesse besteht (Art. 6 Abs. 1 lit. f DSGVO), Sie in die Datenverarbeitung eingewilligt haben (Art. 6 Abs. 1 lit. a DSGVO), die Verarbeitung für die Anbahnung, Begründung, inhaltliche Ausgestaltung oder Änderung eines Rechtsverhältnisses zwischen Ihnen und uns erforderlich sind (Art. 6 Abs. 1 lit. b DSGVO) oder eine sonstige Rechtsnorm die Verarbeitung gestattet. Ihre personenbezogenen Daten verbleiben bei uns, bis Sie uns zur Löschung auffordern, Ihre Einwilligung zur Speicherung widerrufen oder der Zweck für die Datenspeicherung entfällt (z.B. nach abgeschlossener Bearbeitung Ihres Anliegens). Zwingende gesetzliche Bestimmungen – insbesondere steuer- und handelsrechtliche Aufbewahrungsfristen – bleiben unberührt. Sie haben jederzeit das Recht, unentgeltlich Auskunft über Herkunft, Empfänger und Zweck Ihrer gespeicherten personenbezogenen Daten zu erhalten. Ihnen steht außerdem ein Recht auf Widerspruch, auf Datenübertragbarkeit und ein Beschwerderecht bei der zuständigen Aufsichtsbehörde zu. Ferner können Sie die Berichtigung, die Löschung und unter bestimmten Umständen die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten verlangen. 
Details entnehmen Sie unserer Datenschutzerklärung (https://joerggudehus.de/dsgvo.html).

Hier können Sie sich AnyDesk zur Fernwartung herunterladen

https://get.anydesk.com/BEI2iuF8/AnyDesk-gudehus.dmg

**Comment by mdominguez** [comment]
Oh ok, thanks! Better edit the README.md then too ;) [screenshot readme](https://cl.ly/883b8c374b7d)

**Comment by gudehus** [comment]
Oh, thank you I just kept looking at the top of the read.me <http://read.me/>


mit freundlichen Grüßen
Jörg Gudehus

IT-Consultant

Holsteinische Straße 4
10717 Berlin
+49 151 15674619
gudehus@mac.com
www.joerggudehus.de


Pflichtinformationen gemäß Artikel 13 DSGVO
Im Falle des Erstkontakts sind wir gemäß Art. 12, 13 DSGVO verpflichtet, Ihnen folgende datenschutzrechtliche Pflichtinformationen zur Verfügung zu stellen: Wenn Sie uns per E-Mail kontaktieren, verarbeiten wir Ihre personenbezogenen Daten nur, soweit an der Verarbeitung ein berechtigtes Interesse besteht (Art. 6 Abs. 1 lit. f DSGVO), Sie in die Datenverarbeitung eingewilligt haben (Art. 6 Abs. 1 lit. a DSGVO), die Verarbeitung für die Anbahnung, Begründung, inhaltliche Ausgestaltung oder Änderung eines Rechtsverhältnisses zwischen Ihnen und uns erforderlich sind (Art. 6 Abs. 1 lit. b DSGVO) oder eine sonstige Rechtsnorm die Verarbeitung gestattet. Ihre personenbezogenen Daten verbleiben bei uns, bis Sie uns zur Löschung auffordern, Ihre Einwilligung zur Speicherung widerrufen oder der Zweck für die Datenspeicherung entfällt (z.B. nach abgeschlossener Bearbeitung Ihres Anliegens). Zwingende gesetzliche Bestimmungen – insbesondere steuer- und handelsrechtliche Aufbewahrungsfristen – bleiben unberührt. Sie haben jederzeit das Recht, unentgeltlich Auskunft über Herkunft, Empfänger und Zweck Ihrer gespeicherten personenbezogenen Daten zu erhalten. Ihnen steht außerdem ein Recht auf Widerspruch, auf Datenübertragbarkeit und ein Beschwerderecht bei der zuständigen Aufsichtsbehörde zu. Ferner können Sie die Berichtigung, die Löschung und unter bestimmten Umständen die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten verlangen. 
Details entnehmen Sie unserer Datenschutzerklärung (https://joerggudehus.de/dsgvo.html).

Hier können Sie sich AnyDesk zur Fernwartung herunterladen

https://get.anydesk.com/BEI2iuF8/AnyDesk-gudehus.dmg
